name: 'Setup Git'

description: 'Setup Git'

runs:
  using: "composite"
  steps:
    - name: Setup git
      shell: bash
      run: |
        git config --global user.email "bot@raycast.com"
        git config --global user.name "raycastbot"