name: 'Generate vars for CLI'

description: 'Generate vars for CLI'

outputs:
  paths:
    description: "paths"
    value: ${{ steps.generate_vars.outputs.paths }}
  command:
    description: "command"
    value: ${{ steps.generate_vars.outputs.command }}
runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1.1.3
    - name: Generate paths and command
      shell: bash
      id: generate_vars
      run: |
        command=$(${{ github.action_path }}/command.sh "${{ github.event_name }}" "${{ github.event.inputs.command }}")
        echo "::set-output name=command::$command"
        
        paths=$(${{ github.action_path }}/paths.sh "${{ github.event_name }}" "${{ steps.changed-files.outputs.all_modified_files }}" "${{ github.event.inputs.paths }}")
        echo "::set-output name=paths::$paths"