name: "Extensions build & publis"

description: "Extensions build & publis"

inputs:
  access_token:
    description: "Access Token"
    required: false
  command:
    description: "Ray CLI command (build | publish)"
    required: false
  paths:
    description: "Paths to execute on"
    required: false
  cli_version:
    description: "CLI Version"
    required: false
  npm_token:
    description: "NPM token"
    required: false
  extension_schema:
    description: "Extension schema"
    required: false
outputs:
  command:
    description: "Ray CLI command executed"
    value: ${{ steps.get_command.outputs.command }}
  paths:
    description: "Paths for changed extensions"
    value: ${{ steps.get_changed_extensions.outputs.paths }}
  store_urls:
    description: "Store URLs for published extensions"
    value: ${{ steps.ray_cli.outputs.store_urls }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: raycast/github-actions/git-checkout@v1.11.0
    - name: Setup CLI
      uses: raycast/github-actions/setup-cli@v1.11.0
      with:
        version: ${{ inputs.cli_version || '1.40.0-alpha.40' }}
        access_token: ${{ inputs.access_token }}
    - name: Get command
      id: get_command
      uses: raycast/github-actions/get-command@v1.11.0
      with:
        custom_command: ${{ inputs.command }}
        github_event_name: ${{ github.event_name }}
    - name: Get changed extensions
      id: get_changed_extensions
      uses: raycast/github-actions/get-changed-extensions@v1.11.0
      with:
        custom_paths: ${{ inputs.paths }}
        github_event_name: ${{ github.event_name }}
    - name: Ray CLI
      id: ray_cli
      uses: raycast/github-actions/ray-cli@v1.11.0
      with:
        paths: ${{ steps.get_changed_extensions.outputs.paths }}
        command: ${{ steps.get_command.outputs.command }}
        npm_token: ${{ inputs.npm_token }}
        extension_schema: ${{ inputs.extension_schema }}
