name: "Setup Raycast CLI"

description: "Setup Raycast CLI"

inputs:
  version:
    description: "CLI version (format: v1.0.0)"
    required: true
  access_token:
    description: "Access Token"
    required: false
  api_url:
    description: "API url"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup CLI
      shell: bash
      run: |
        ${{ github.action_path }}/setup_cli.sh "${{ inputs.version }}" "${{ inputs.access_token }}" "${{ inputs.api_url }}"
