name: 'Setup Raycast CLI'

description: 'Setup Raycast CLI'

inputs:
  access_token:
    description: 'Access Token'
    required: true
  api_url:
    description: 'API url'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup CLI
      shell: bash
      run: |
        ${{ github.action_path }}/setup_cli.sh "${{ inputs.access_token }}" "${{ inputs.api_url }}"