name: "Setup Xcode"

description: "Setup Xcode"

runs:
  using: "composite"
  steps:
    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.2.x
