name: "Setup NPM for Raycast"

description: "Setup NPM for Raycast"

runs:
  using: "composite"
  steps:
    - name: Setup npm
      shell: bash
      run: |
        npm install npm@8.3.0 --location=global
        which npm
        npm -v
