name: "Get command to execute on CLI based on github_event_name"

description: "Get command to execute on CLI based on github_event_name"

inputs:
  custom_command:
    description: "User defined custom command for workflow_dispatch"
  github_event_name:
    description: "github.event_name"
outputs:
  command:
    description: "command"
    value: ${{ steps.calculate_command.outputs.command }}
runs:
  using: "composite"
  steps:
    - name: Calculate command
      id: calculate_command
      uses: actions/github-script@v6
      with:
        script: |
          let event_name = "${{ inputs.github_event_name }}";
          let command;
          if (event_name === 'push') {
            command = 'publish';
          } else if (event_name === 'pull_request') {
            command = 'build';
          } else {
            command = "${{ inputs.custom_command }}";
          }
          core.setOutput("command", command);
