name: "Raycast CLI"

description: "Raycast CLI"

inputs:
  paths:
    description: "Paths to execute on"
    required: true
  command:
    description: "Ray CLI command (build | publish)"
    required: true
  npm_token:
    description: "NPM token"
    required: false
outputs:
  store_urls:
    description: "Store URLs for published extensions"
    value: ${{ steps.ray_cli.outputs.store_urls }}
runs:
  using: "composite"
  steps:
    - name: Install npm
      uses: raycast/github-actions/setup-npm@v1.7.0
    - name: Execute command
      shell: bash
      id: ray_cli
      env:
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE
      run: |
        set -e -o noglob
        ${{ github.action_path }}/ray_cli.sh "${{ inputs.command }}" "${{ inputs.paths }}" "${{ inputs.npm_token }}"
