name: 'Raycast CLI'

description: 'Raycast CLI'

inputs:
  paths:
    description: 'Paths to execute on'
    required: true
  command:
    description: 'Ray CLI command (build | publish)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install npm
      uses: raycast/github-actions/setup-npm@v1.0.0
    - name: Execute command
      shell: bash
      env:
        GITHUB_WORKSPACE: $GITHUB_WORKSPACE
      run: |
        set -e -o noglob
        ${{ github.action_path }}/ray_cli.sh "${{ inputs.command }}" "${{ inputs.paths }}"